# Generated by Django 4.2.28 on 2026-02-22 02:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('session_key', models.CharField(db_index=True, max_length=255)),
                ('usage_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'anonymous_sessions',
                'unique_together': {('email', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('tool_name', models.CharField(max_length=100)),
                ('filename', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='usage_logs_user_id_dcf91c_idx'), models.Index(fields=['session_key', 'email'], name='usage_logs_session_f9243c_idx'), models.Index(fields=['created_at'], name='usage_logs_created_4640f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_email', models.CharField(max_length=255)),
                ('meaning', models.CharField(choices=[('approved', 'Approved'), ('reviewed', 'Reviewed'), ('authored', 'Authored'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('acknowledged', 'Acknowledged')], max_length=50)),
                ('document_name', models.CharField(max_length=500)),
                ('document_hash_before', models.CharField(max_length=128)),
                ('document_hash_after', models.CharField(max_length=128)),
                ('output_file', models.CharField(blank=True, default='', max_length=500)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('page_number', models.IntegerField(default=1)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('record_checksum', models.CharField(blank=True, default='', max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signature_records',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['signer_email', 'signed_at'], name='signature_r_signer__8c3929_idx'), models.Index(fields=['document_name'], name='signature_r_documen_26c69c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('sign', 'Document Signed'), ('login', 'User Login'), ('login_failed', 'Login Failed'), ('logout', 'User Logout'), ('create_user', 'User Created'), ('edit_user', 'User Edited'), ('delete_user', 'User Deleted'), ('tool_use', 'Tool Used'), ('download', 'File Downloaded'), ('password_change', 'Password Changed'), ('session_start', 'Session Started'), ('limit_reached', 'Usage Limit Reached')], max_length=50)),
                ('detail', models.TextField(blank=True, default='')),
                ('document_name', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_trail',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_trail_action_3537bd_idx'), models.Index(fields=['user', 'timestamp'], name='audit_trail_user_id_d519bc_idx'), models.Index(fields=['email'], name='audit_trail_email_9015fa_idx')],
            },
        ),
    ]
